### ISSUE TITLE
Incompatible with some mods/server 

### ISSUE THREAD

**Issue by Scarlaid** [zomabies/RestoreChatLinks#1]
![image](https://user-images.githubusercontent.com/90851437/207061373-817d035f-2186-4cec-8ea0-ce3c0b7b6a65.png)

If you have RCL installed, some mods like Celestria will have a blank chat (the second line from the top to bottom)
same goes with some servers with chat annoucements

**Comment by zomabies** [comment]
Hi, I have fixed the issue, can you please update to the latest version and see if the bug still persists?

**Comment by Scarlaid** [comment]
the bug is indeed fixed in the latest release, mentioned mod above now display the chat normally, same with any server I have joined has chat annoucements
![image](https://user-images.githubusercontent.com/90851437/207209232-7a7f2e78-f55d-47c3-a063-7e25ae2e1784.png)
![image](https://user-images.githubusercontent.com/90851437/207209199-a831529a-8eec-4de4-b68f-315ff494b131.png)
