### ISSUE TITLE
Links are not recognised. 

### ISSUE THREAD

**Issue by luk4k0** [zomabies/RestoreChatLinks#6]
Hello, 

I am running Restore Chat links on 1.20.1. I have a forge, but also Sinytra connector which enables loading Fabric mods. 

When I paste a link into the chat like "example.com" it recognises it but it adds "7" before it. As an image shows. Links like Bluemap links its does not recognise at all.

Thank you for any help!
 
![2024-01-29_18 14 50](https://github.com/zomabies/RestoreChatLinks/assets/113149282/8631210c-a98a-4cde-9104-294c7bcb2d4e)

**Comment by zomabies** [comment]
Hi, please enable debug message in config and upload `latest.log` after reproduce it.

**Comment by luk4k0** [comment]
[latest.log](https://github.com/zomabies/RestoreChatLinks/files/14117543/latest.log)

So there is debug mode turned on in restorechatlinks config, not sure it works tho :D Latest messages in the logg are those links I tried in ingame chat. Let me know if the debug works. Thank you for help.

**Comment by zomabies** [comment]
I have read the log, but this is server log. Can you send the client log that you have reproduced?

**Comment by luk4k0** [comment]
[latest.log](https://github.com/zomabies/RestoreChatLinks/files/14151375/latest.log)

This is the client latest.log. It is in the end of the file. Hope it helps. Thank you.

**Comment by zomabies** [comment]
Unfortunately, it is still server log but no worries. You can provide me the mod list.

But if you able to repeat the steps in the client, that will be better.
1. repeat the steps just like in the screenshot
2. get `logs/debug.log` from your Minecraft directory

**Comment by zomabies** [comment]
You can ignore my reply above, I have found the issue. It is a issue with [SimpleChat (fork)](https://modrinth.com/mod/simplechatfork).

As a workaround, you can type anything before a link, example:  

![workaround](https://i.imgur.com/I13QUii.png)

**Comment by luk4k0** [comment]
Thank you, that will resolve the issue for me I think.

**Comment by zomabies** [comment]
Fixed in latest version with `convertFormattingCode` enabled.

![](https://i.imgur.com/SmYNHQt.png)

**Comment by luk4k0** [comment]
Thank you, I will try it tomorrow!
