### ISSUE TITLE
[Suggestion] Color & Underline for Screenshots

### ISSUE THREAD

**Issue by nco2k** [zomabies/RestoreChatLinks#9]
would be cool if the color and underline options would also affect screenshot links.

**Comment by zomabies** [comment]
Sorry to ask but have you read the mod's description?

**Comment by nco2k** [comment]
yes, and screenshots are clickable chat links, which your mod can change the appearance of.

**Comment by zomabies** [comment]
I just realised that the suggestion is to add a feature that allows screenshot link to match with the mod's config.
Unfortunately, it is not within the scope of this mod.
